import fs from 'fs/promises';
import path from 'path';
import type { EvolveConfig, Task } from './types.js';

/**
 * Creates the .kairn-evolve/ directory structure.
 * Returns the path to the workspace.
 */
export async function createEvolveWorkspace(
  projectRoot: string,
  config: EvolveConfig,
): Promise<string> {
  const workspace = path.join(projectRoot, '.kairn-evolve');

  // Create directories
  await fs.mkdir(path.join(workspace, 'baseline'), { recursive: true });
  await fs.mkdir(path.join(workspace, 'traces'), { recursive: true });
  await fs.mkdir(path.join(workspace, 'iterations'), { recursive: true });

  // Write config.yaml
  const configYaml = `model: ${config.model}
proposer_model: ${config.proposerModel}
scorer: ${config.scorer}
max_iterations: ${config.maxIterations}
parallel_tasks: ${config.parallelTasks}`;

  await fs.writeFile(path.join(workspace, 'config.yaml'), configYaml, 'utf-8');

  return workspace;
}

/**
 * Writes tasks.yaml to the workspace.
 */
export async function writeTasksFile(
  workspacePath: string,
  tasks: Task[],
): Promise<void> {
  let yaml = '# .kairn-evolve/tasks.yaml\n';
  yaml += '# Auto-generated by kairn evolve init — edit freely\n';
  yaml += 'tasks:\n';

  for (const task of tasks) {
    yaml += `  - id: ${task.id}\n`;
    yaml += `    template: ${task.template}\n`;
    yaml += `    description: "${task.description}"\n`;
    yaml += `    setup: |\n`;
    for (const line of task.setup.split('\n')) {
      yaml += `      ${line}\n`;
    }
    yaml += `    expected_outcome: |\n`;
    const outcomes = Array.isArray(task.expected_outcome)
      ? task.expected_outcome
      : task.expected_outcome.split('\n');
    for (const outcome of outcomes) {
      yaml += `      - ${outcome}\n`;
    }
    yaml += `    scoring: ${task.scoring}\n`;
    if (task.rubric) {
      yaml += `    rubric:\n`;
      for (const criterion of task.rubric) {
        yaml += `      - criterion: "${criterion.criterion}"\n`;
        yaml += `        weight: ${criterion.weight}\n`;
      }
    }
    yaml += `    timeout: ${task.timeout}\n`;
    yaml += '\n';
  }

  await fs.writeFile(path.join(workspacePath, 'tasks.yaml'), yaml, 'utf-8');
}
