import os from "os";
import type { EnvironmentSpec, RegistryTool } from "../types.js";
import {
  createRenderedHarness,
  writeRenderedHarness,
  type RenderedHarness,
  type RenderedHarnessEntry,
} from "../rendered-harness.js";

function toYaml(obj: unknown, indent: number = 0): string {
  const pad = "  ".repeat(indent);

  if (obj === null || obj === undefined) {
    return "~";
  }

  if (typeof obj === "boolean") {
    return obj ? "true" : "false";
  }

  if (typeof obj === "number") {
    return String(obj);
  }

  if (typeof obj === "string") {
    // Quote strings that contain special characters or look like other types
    const needsQuotes =
      obj === "" ||
      /[:#\[\]{}&*!|>'"%@`,]/.test(obj) ||
      /^(true|false|null|~|\d)/.test(obj) ||
      obj.includes("\n");
    return needsQuotes ? `"${obj.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"` : obj;
  }

  if (Array.isArray(obj)) {
    if (obj.length === 0) {
      return "[]";
    }
    return obj
      .map((item) => `${pad}- ${toYaml(item, indent + 1).trimStart()}`)
      .join("\n");
  }

  if (typeof obj === "object") {
    const entries = Object.entries(obj as Record<string, unknown>);
    if (entries.length === 0) {
      return "{}";
    }
    return entries
      .map(([key, value]) => {
        const valueStr = toYaml(value, indent + 1);
        const isScalar =
          typeof value !== "object" || value === null || Array.isArray(value);
        if (isScalar && !Array.isArray(value)) {
          return `${pad}${key}: ${valueStr}`;
        }
        if (Array.isArray(value)) {
          if ((value as unknown[]).length === 0) {
            return `${pad}${key}: []`;
          }
          return `${pad}${key}:\n${valueStr}`;
        }
        return `${pad}${key}:\n${valueStr}`;
      })
      .join("\n");
  }

  return String(obj);
}

function buildMcpServersYaml(
  spec: EnvironmentSpec,
  registry: RegistryTool[]
): string {
  const servers: Record<string, unknown> = {};

  // For each selected tool, check for hermes-specific mcp_server config first
  for (const selected of spec.tools) {
    const tool = registry.find((t) => t.id === selected.tool_id);
    if (!tool) continue;

    if (tool.install.hermes?.mcp_server) {
      const serverName = tool.id.replace(/_/g, "-");
      servers[serverName] = tool.install.hermes.mcp_server;
    } else if (tool.install.mcp_config) {
      // Fall back to converting the Claude Code mcp_config format
      for (const [serverName, serverConfig] of Object.entries(
        tool.install.mcp_config
      )) {
        servers[serverName] = serverConfig;
      }
    }
  }

  // Also include any mcp_config entries from the harness that weren't covered by tools
  for (const [serverName, serverConfig] of Object.entries(
    spec.harness.mcp_config || {}
  )) {
    if (!(serverName in servers)) {
      servers[serverName] = serverConfig;
    }
  }

  if (Object.keys(servers).length === 0) {
    return "";
  }

  const lines: string[] = [];
  lines.push(`# Generated by Kairn v1.5.0`);
  lines.push(`# Environment: ${spec.name}`);
  lines.push(``);
  lines.push(`mcp_servers:`);

  for (const [serverName, serverConfig] of Object.entries(servers)) {
    lines.push(`  ${serverName}:`);
    lines.push(toYaml(serverConfig, 2));
  }

  return lines.join("\n") + "\n";
}

export async function writeHermesEnvironment(
  spec: EnvironmentSpec,
  registry: RegistryTool[]
): Promise<string[]> {
  return writeRenderedHarness(
    buildHermesRenderedHarness(spec, registry),
    os.homedir(),
  );
}

export function buildHermesRenderedHarness(
  spec: EnvironmentSpec,
  registry: RegistryTool[],
): RenderedHarness {
  const files: RenderedHarnessEntry[] = [];

  // 1. config.yaml
  const configYaml = buildMcpServersYaml(spec, registry);
  if (configYaml) {
    files.push({
      path: ".hermes/config.yaml",
      content: configYaml,
      source: "mcp",
    });
  }

  // 2. Skills from commands
  if (spec.harness.commands) {
    for (const [name, content] of Object.entries(spec.harness.commands)) {
      files.push({
        path: `.hermes/skills/${name}.md`,
        content,
        source: "commands",
      });
    }
  }

  // 3. Skills from skills
  if (spec.harness.skills) {
    for (const [name, content] of Object.entries(spec.harness.skills)) {
      files.push({
        path: `.hermes/skills/${name}.md`,
        content,
        source: "skills",
      });
    }
  }

  // 4. Skills from rules (prefixed with "rule-")
  if (spec.harness.rules) {
    for (const [name, content] of Object.entries(spec.harness.rules)) {
      files.push({
        path: `.hermes/skills/rule-${name}.md`,
        content,
        source: "rules",
      });
    }
  }

  return createRenderedHarness(files, { target: "hermes", source: "environment-spec" });
}
