import { Command } from "commander";
import { password } from "@inquirer/prompts";
import chalk from "chalk";
import { ui } from "../ui.js";
import { printCompactBanner } from "../logo.js";
import {
  detectRequiredEnvVars,
  readEnvFile,
  collectAndWriteKeys,
} from "../secrets.js";
import { loadRegistry } from "../registry/loader.js";
import type { EnvSetupInfo } from "../adapter/claude-code.js";
import fs from "fs/promises";
import path from "path";

export const keysCommand = new Command("keys")
  .description("Add or update API keys for the current environment")
  .option("--show", "Show which keys are set vs missing")
  .action(async (options: { show?: boolean }) => {
    printCompactBanner();

    const targetDir = process.cwd();

    // 1. Detect required env vars from .mcp.json
    const requiredVars = await detectRequiredEnvVars(targetDir);

    if (requiredVars.length === 0) {
      console.log(
        ui.info("No MCP servers found in .mcp.json — no API keys needed.")
      );
      console.log("");
      return;
    }

    // 2. Read existing .env
    const existing = await readEnvFile(targetDir);

    // 3. Build env setup info from registry for richer display
    const registry = await loadRegistry();
    const envSetupMap = new Map<string, EnvSetupInfo>();
    for (const tool of registry) {
      if (!tool.env_vars) continue;
      for (const ev of tool.env_vars) {
        if (requiredVars.includes(ev.name)) {
          envSetupMap.set(ev.name, {
            toolName: tool.name,
            envVar: ev.name,
            description: ev.description,
            signupUrl: tool.signup_url,
          });
        }
      }
    }

    // Fill in any vars not found in registry
    for (const varName of requiredVars) {
      if (!envSetupMap.has(varName)) {
        envSetupMap.set(varName, {
          toolName: "unknown",
          envVar: varName,
          description: "Required by MCP server",
        });
      }
    }

    // 4. --show mode: display status and exit
    if (options.show) {
      console.log(ui.section("API Key Status"));
      console.log("");

      for (const varName of requiredVars) {
        const value = existing.get(varName);
        const info = envSetupMap.get(varName);
        const toolLabel = info?.toolName !== "unknown" ? chalk.dim(` (${info?.toolName})`) : "";

        if (value && value.length > 0) {
          const masked = value.slice(0, 4) + "•".repeat(Math.max(0, value.length - 4));
          console.log(chalk.green(`  ✓ ${varName}`) + toolLabel + chalk.dim(` = ${masked}`));
        } else {
          console.log(chalk.yellow(`  ✗ ${varName}`) + toolLabel + chalk.dim(" = (not set)"));
          if (info?.signupUrl) {
            console.log(chalk.dim(`      Get one at: ${info.signupUrl}`));
          }
        }
      }

      const setCount = requiredVars.filter((v) => {
        const val = existing.get(v);
        return val && val.length > 0;
      }).length;
      const missingCount = requiredVars.length - setCount;

      console.log("");
      if (missingCount === 0) {
        console.log(ui.success(`All ${setCount} key(s) configured`));
      } else {
        console.log(
          ui.warn(`${missingCount} key(s) missing — run ${chalk.bold("kairn keys")} to add them`)
        );
      }
      console.log("");
      return;
    }

    // 5. Interactive mode: prompt for missing or empty keys
    const missing = requiredVars.filter((v) => {
      const val = existing.get(v);
      return !val || val.length === 0;
    });

    if (missing.length === 0) {
      console.log(ui.success("All API keys are already configured."));
      console.log(chalk.dim("  Use --show to see current keys.\n"));
      return;
    }

    console.log(ui.section("API Keys"));
    console.log(chalk.dim(`  ${missing.length} key(s) need to be set. Press Enter to skip.\n`));

    const envEntries = new Map(existing);
    let keysEntered = 0;

    for (const varName of missing) {
      const info = envSetupMap.get(varName);

      console.log(
        chalk.bold(`  ${varName}`) +
          (info?.toolName !== "unknown" ? chalk.dim(` (${info?.toolName})`) : "")
      );
      if (info?.signupUrl) {
        console.log(chalk.dim(`    Get one at: ${info.signupUrl}`));
      }

      const value = await password({
        message: varName,
        mask: "•",
      });

      if (value && value.trim()) {
        envEntries.set(varName, value.trim());
        console.log(chalk.green("  ✓ saved\n"));
        keysEntered++;
      } else {
        console.log(chalk.dim("  (skipped)\n"));
      }
    }

    // 6. Write updated .env
    const envLines: string[] = [
      "# Generated by Kairn — API keys for MCP servers",
      "# Do NOT commit this file to git",
      "",
    ];
    for (const [key, value] of envEntries) {
      envLines.push(`${key}=${value}`);
    }

    const envPath = path.join(targetDir, ".env");
    await fs.writeFile(envPath, envLines.join("\n") + "\n", "utf-8");

    console.log(chalk.green(`  ✓ ${keysEntered} key(s) saved to .env`));
    console.log("");
  });
