import { password } from "@inquirer/prompts";
import chalk from "chalk";
import fs from "fs/promises";
import path from "path";
import { ui } from "./ui.js";
import type { EnvSetupInfo } from "./adapter/claude-code.js";

export interface KeyCollectionResult {
  keysEntered: number;
  keysSkipped: number;
  envPath: string;
}

/**
 * Interactively prompt the user for API keys and write a .env file.
 * Skipped keys get empty placeholders. Also updates .gitignore.
 */
export async function collectAndWriteKeys(
  envSetup: EnvSetupInfo[],
  targetDir: string
): Promise<KeyCollectionResult> {
  console.log(ui.section("API Keys"));
  console.log(
    chalk.dim("  Some tools need API keys. Enter them now or press Enter to skip.\n")
  );

  const envEntries: string[] = [
    "# Generated by Kairn — API keys for MCP servers",
    "# Do NOT commit this file to git",
    "",
  ];

  let keysEntered = 0;
  let keysSkipped = 0;
  const seen = new Set<string>();

  for (const env of envSetup) {
    if (seen.has(env.envVar)) continue;
    seen.add(env.envVar);

    console.log(chalk.bold(`  ${env.envVar}`) + chalk.dim(` (${env.toolName})`));
    if (env.signupUrl) {
      console.log(chalk.dim(`    Get one at: ${env.signupUrl}`));
    }

    const value = await password({
      message: env.envVar,
      mask: "•",
    });

    if (value && value.trim()) {
      envEntries.push(`${env.envVar}=${value.trim()}`);
      console.log(chalk.green("  ✓ saved\n"));
      keysEntered++;
    } else {
      envEntries.push(`${env.envVar}=`);
      console.log(chalk.dim("  (skipped)\n"));
      keysSkipped++;
    }
  }

  // Write .env file
  const envPath = path.join(targetDir, ".env");
  await fs.writeFile(envPath, envEntries.join("\n") + "\n", "utf-8");

  // Update .gitignore
  await ensureGitignoreEntry(targetDir, ".env");

  console.log(chalk.green(`  ✓ ${keysEntered} key(s) saved to .env (gitignored)`));
  if (keysSkipped > 0) {
    console.log(chalk.dim("  Skipped keys can be added later: kairn keys"));
  }

  return { keysEntered, keysSkipped, envPath };
}

/**
 * Write a .env file with empty placeholders for all keys (no prompts).
 * Used with --quick flag.
 */
export async function writeEmptyEnvFile(
  envSetup: EnvSetupInfo[],
  targetDir: string
): Promise<void> {
  const envEntries: string[] = [
    "# Generated by Kairn — API keys for MCP servers",
    "# Do NOT commit this file to git",
    "",
  ];

  const seen = new Set<string>();
  for (const env of envSetup) {
    if (seen.has(env.envVar)) continue;
    seen.add(env.envVar);
    envEntries.push(`${env.envVar}=`);
  }

  const envPath = path.join(targetDir, ".env");
  await fs.writeFile(envPath, envEntries.join("\n") + "\n", "utf-8");
  await ensureGitignoreEntry(targetDir, ".env");
}

/**
 * Ensure a line exists in .gitignore. Creates the file if needed.
 */
async function ensureGitignoreEntry(
  targetDir: string,
  entry: string
): Promise<void> {
  const gitignorePath = path.join(targetDir, ".gitignore");
  let gitignore = "";
  try {
    gitignore = await fs.readFile(gitignorePath, "utf-8");
  } catch {
    // File doesn't exist yet
  }
  if (!gitignore.split("\n").some((line) => line.trim() === entry)) {
    const separator = gitignore.length > 0 && !gitignore.endsWith("\n") ? "\n" : "";
    await fs.writeFile(gitignorePath, gitignore + separator + entry + "\n", "utf-8");
  }
}

/**
 * Parse an existing .env file and return key-value pairs.
 */
export async function readEnvFile(
  targetDir: string
): Promise<Map<string, string>> {
  const envPath = path.join(targetDir, ".env");
  const entries = new Map<string, string>();
  try {
    const content = await fs.readFile(envPath, "utf-8");
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIndex = trimmed.indexOf("=");
      if (eqIndex === -1) continue;
      const key = trimmed.slice(0, eqIndex);
      const value = trimmed.slice(eqIndex + 1);
      entries.set(key, value);
    }
  } catch {
    // File doesn't exist
  }
  return entries;
}

/**
 * Parse .mcp.json to find which env vars are needed.
 */
export async function detectRequiredEnvVars(
  targetDir: string
): Promise<string[]> {
  const mcpPath = path.join(targetDir, ".mcp.json");
  const envVars = new Set<string>();
  try {
    const content = await fs.readFile(mcpPath, "utf-8");
    // Match ${ENV_VAR} patterns in the MCP config
    const matches = content.matchAll(/\$\{([A-Z_][A-Z0-9_]*)\}/g);
    for (const match of matches) {
      envVars.add(match[1]);
    }
  } catch {
    // No .mcp.json
  }
  return [...envVars];
}

/**
 * Get unique env setup entries (deduplicated by envVar).
 */
export function dedupeEnvSetup(envSetup: EnvSetupInfo[]): EnvSetupInfo[] {
  const seen = new Set<string>();
  return envSetup.filter((e) => {
    if (seen.has(e.envVar)) return false;
    seen.add(e.envVar);
    return true;
  });
}
